/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PAKET;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Funda DURU
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
        getContentPane().setBackground(Color.cyan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sogutucuyuKapatButon = new javax.swing.JButton();
        sicaklikGoruntuleButon = new javax.swing.JButton();
        sogutucuyuAcButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sogutucuyuKapatButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sogutucuyuKapatButon.setForeground(new java.awt.Color(0, 0, 102));
        sogutucuyuKapatButon.setText("Soğutucuyu Kapat");
        sogutucuyuKapatButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sogutucuyuKapatButonActionPerformed(evt);
            }
        });

        sicaklikGoruntuleButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sicaklikGoruntuleButon.setForeground(new java.awt.Color(0, 0, 102));
        sicaklikGoruntuleButon.setText("Sıcaklık Görüntüle");
        sicaklikGoruntuleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sicaklikGoruntuleButonActionPerformed(evt);
            }
        });

        sogutucuyuAcButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sogutucuyuAcButon.setForeground(new java.awt.Color(0, 0, 102));
        sogutucuyuAcButon.setText("Soğutucuyu Aç");
        sogutucuyuAcButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sogutucuyuAcButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sicaklikGoruntuleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sogutucuyuKapatButon)
                        .addGap(18, 18, 18)
                        .addComponent(sogutucuyuAcButon)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sogutucuyuKapatButon)
                    .addComponent(sogutucuyuAcButon))
                .addGap(99, 99, 99)
                .addComponent(sicaklikGoruntuleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    GIRIS giris=new GIRIS();
    private void sogutucuyuKapatButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sogutucuyuKapatButonActionPerformed
        if(giris.yetKisi.getSogutucu().getDurum()==false)
        JOptionPane.showMessageDialog(null,"Soğutucu zaten kapalı.");
       
        else
        {
            giris.yetKisi.getSogutucu().sogutucuyuKapat();
            JOptionPane.showMessageDialog(null,"Soğutucu kapatıldı.");
        }
    }//GEN-LAST:event_sogutucuyuKapatButonActionPerformed

    private void sicaklikGoruntuleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sicaklikGoruntuleButonActionPerformed
        Sicaklik sicaklik=Sicaklik.getSicaklik();
        sicaklik.sicaklikUret();
    }//GEN-LAST:event_sicaklikGoruntuleButonActionPerformed

    private void sogutucuyuAcButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sogutucuyuAcButonActionPerformed
        if(giris.yetKisi.getSogutucu().getDurum()==true)
        JOptionPane.showMessageDialog(null,"Soğutucu zaten açık.");

        else
        {
            giris.yetKisi.getSogutucu().sogutucuyuAc();
            JOptionPane.showMessageDialog(null,"Soğutucu açıldı");
        }
    }//GEN-LAST:event_sogutucuyuAcButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton sicaklikGoruntuleButon;
    private javax.swing.JButton sogutucuyuAcButon;
    private javax.swing.JButton sogutucuyuKapatButon;
    // End of variables declaration//GEN-END:variables
}
